### ISSUE TITLE
info: Nav2 build error 

### ISSUE THREAD

**Issue by AshinTheAnvil** [muttistefano/azrael_driver_udp#1]
Hi @muttistefano ,

This is Ashin. We had recently worked on an issue on nav2 build. 
I just have some few queries on it. Actually  I had tried it building on ubuntu 22 and I faced the issue You had faced on Ubuntu 18. Now after changing certain lines in certain packages, I was able to build it.
I work with Virtual machine btw..
Like is it working for you without altering the lines in ubuntu 22?
Hope you reply and sorry for starting issue in your active repository, I was not able to find your email.

Thanks

**Comment by muttistefano** [comment]
Hi @AshinTheAnvil ,
I tried on Ubuntu 22, using the ros rolling version installed from the repository, and the main branch of the navigation2 compiled 
 correctly.
I don't know if Working in a virtual machine changes something.
When i was on ubuntu 18 i wasn't able to track down the problem. to the source, hence, following the template resolution through rclcpp.
When i was on ubuntu 18 i had ros rolling build from scratch but everything was up to date.
I even tried to use a newer GCC version than the one provided on Ubuntu 18 but it didn't work.
If the changes we tried work for you is fine i guess, since then i decided to pass to ubuntu 22 to solve all of this.

**Comment by AshinTheAnvil** [comment]
Yeah Thanks for your reply.
There was a similar issue for a person working on mac using Virtual machine longback.
Also are you working on a virtual machine?

**Comment by muttistefano** [comment]
Nono I'm working directly in ubuntu.

**Comment by AshinTheAnvil** [comment]
I see, Well VM are always a bit tricky.
Thanks for all your help @muttistefano  and Best wishes.

**Comment by muttistefano** [comment]
U too :)
